### PR TITLE
feat: Upgraded to latest version of singer_sdk, fixed upper case columns with column alters

### LINKED ISSUE #152: Alter Table with Upper case in stream name causes issues
```
❯ meltano run tap-oracle target-postgres
2023-06-26T16:54:20.442922Z [info     ] Environment 'dev' is active
2023-06-26T16:54:26.167243Z [warning  ] No state was found, complete import.
2023-06-26T16:54:26.313384Z [info     ] time=2023-06-26 18:54:26 name=singer level=INFO message=Selected streams: ['BUSINESSDATA_PROD-CHANNEL'] cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-26T16:54:26.313704Z [info     ] time=2023-06-26 18:54:26 name=singer level=INFO message=No currently_syncing found cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-26T16:54:26.313904Z [info     ] time=2023-06-26 18:54:26 name=singer level=INFO message=Beginning sync of stream(BUSINESSDATA_PROD-CHANNEL) with sync method(full) cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-26T16:54:26.314035Z [info     ] time=2023-06-26 18:54:26 name=singer level=INFO message=Stream BUSINESSDATA_PROD-CHANNEL is using full_table replication cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-26T16:54:26.314120Z [info     ] time=2023-06-26 18:54:26 name=singer level=INFO message=dsn: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=redacted)(PORT=redacted))(CONNECT_DATA=(SERVICE_NAME=redacted))) cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-26T16:54:26.383916Z [info     ] time=2023-06-26 18:54:26 name=singer level=INFO message=select SELECT  "..redacted.." , ORA_ROWSCN cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-26T16:54:26.384094Z [info     ]                                 FROM BUSINESSDATA_PROD.CHANNEL cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-26T16:54:26.384253Z [info     ]                                ORDER BY ORA_ROWSCN ASC cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-26T16:54:26.394513Z [info     ] time=2023-06-26 18:54:26 name=singer level=INFO message=METRIC: b'{"type":"counter","metric":"record_count","value":150,"tags":{}}' cmd_type=elb consumer=False name=tap-oracle producer=True stdio=stderr string_id=tap-oracle
2023-06-26T16:54:26.580160Z [info     ] 2023-06-26 18:54:26,579 | INFO     | target-postgres      | Target 'target-postgres' is listening for input from tap. cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.580417Z [info     ] 2023-06-26 18:54:26,580 | INFO     | target-postgres      | Initializing 'target-postgres' target sink... cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.580533Z [info     ] 2023-06-26 18:54:26,580 | INFO     | target-postgres      | Initializing target sink for stream 'BUSINESSDATA_PROD-CHANNEL'... cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.756201Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.756444Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1905, in _execute_context cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.757332Z [info     ]     self.dialect.do_execute(   cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.757504Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.757873Z [info     ]     cursor.execute(statement, parameters) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.758041Z [info     ] psycopg2.errors.UndefinedTable: relation "source__icx.channel" does not exist cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.758139Z [info     ]                                cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.758262Z [info     ]                                cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.758422Z [info     ] The above exception was the direct cause of the following exception: cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.758510Z [info     ]                                cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.758668Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.758759Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module> cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.758974Z [info     ]     sys.exit(TargetPostgres.cli()) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.759068Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__ cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.759217Z [info     ]     return self.main(*args, **kwargs) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.759328Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.759422Z [info     ]     rv = self.invoke(ctx)      cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.759503Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.759700Z [info     ]     return ctx.invoke(self.callback, **ctx.params) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.759844Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.759941Z [info     ]     return __callback(*args, **kwargs) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.760028Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 572, in cli cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.760129Z [info     ]     target.listen(file_input)  cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.760236Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/singer_sdk/io_base.py", line 34, in listen cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.760431Z [info     ]     self._process_lines(file_input) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.760553Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 272, in _process_lines cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.760645Z [info     ]     counter = super()._process_lines(file_input) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.760743Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/singer_sdk/io_base.py", line 84, in _process_lines cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.760826Z [info     ]     self._process_activate_version_message(line_dict) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.761036Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 413, in _process_activate_version_message cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.761118Z [info     ]     sink.activate_version(message_dict["version"]) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.761267Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/target_postgres/sinks.py", line 333, in activate_version cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.761527Z [info     ]     self.connector.prepare_column( cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.761608Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/singer_sdk/connectors/sql.py", line 696, in prepare_column cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.761883Z [info     ]     self._create_empty_column( cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.762184Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/singer_sdk/connectors/sql.py", line 638, in _create_empty_column cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.762354Z [info     ]     self.connection.execute(column_add_ddl) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.762503Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1385, in execute cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.762596Z [info     ]     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.762679Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.762943Z [info     ]     return connection._execute_ddl( cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.763105Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.763258Z [info     ]     ret = self._execute_context( cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.763377Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1948, in _execute_context cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.763551Z [info     ]     self._handle_dbapi_exception( cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.763637Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2129, in _handle_dbapi_exception cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.763718Z [info     ]     util.raise_(               cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.763797Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_ cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.763886Z [info     ]     raise exception            cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.763997Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1905, in _execute_context cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.764090Z [info     ]     self.dialect.do_execute(   cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.764203Z [info     ]   File "/path/to/meltano/project/.meltano/loaders/target-postgres/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.764292Z [info     ]     cursor.execute(statement, parameters) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.764388Z [info     ] sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "source__icx.channel" does not exist cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.764470Z [info     ]                                cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.764548Z [info     ] [SQL: ALTER TABLE source__icx.CHANNEL ADD COLUMN _sdc_table_version BIGINT] cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.764628Z [info     ] (Background on this error at: https://sqlalche.me/e/14/f405) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-26T16:54:26.817410Z [error    ] Loader failed
2023-06-26T16:54:26.817708Z [error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError('Loader failed') exit_codes={<PluginType.LOADERS: 'loaders'>: 1} set_number=0 success=False
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.
```
Run invocation could not be completed as block failed: Loader failed

### PR DESCRIPTION
**Pull request by visch**
Closes #152, #103, #124, #2

### CODE REVIEW

**Comment by visch** [comment]
@BuzzCutNorman tried this PR here https://meltano.slack.com/archives/C01RKUVUG4S/p1688075229854589?thread_ts=1688060563.197079&cid=C01RKUVUG4S , I thought this would address an issue like

```
cur.execute(b''.join(parts)) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2023-06-29T20:23:10.757683Z [info     ] sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
```

By using Pooling properly but we're still hitting it. Going to take a look a bit deeper but wanted to capture this somewhere

**Comment by visch** [comment]
> @BuzzCutNorman tried this PR here https://meltano.slack.com/archives/C01RKUVUG4S/p1688075229854589?thread_ts=1688060563.197079&cid=C01RKUVUG4S , I thought this would address an issue like
> 
> ```
> cur.execute(b''.join(parts)) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
> 2023-06-29T20:23:10.757683Z [info     ] sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
> ```
> 
> By using Pooling properly but we're still hitting it. Going to take a look a bit deeper but wanted to capture this somewhere

@BuzzCutNorman  can you try this again?

**Review by edgarrmondragon — COMMENTED** [review]
This looks great 😁

**Comment by visch** [comment]
pre-commit.ci autofix

**Pull request merged**
