### PR TITLE
fix: Implement `NOTYPE.python_type` to fix adapting column types

### PR DESCRIPTION
**Pull request by edgarrmondragon**
Closes https://github.com/MeltanoLabs/target-postgres/issues/237

### CODE REVIEW

**Comment by visch** [comment]
Related to lists I'd assume? I haven't hit this one yet, but the fix looks solid to me.

**Comment by edgarrmondragon** [comment]
> Related to lists I'd assume? I haven't hit this one yet, but the fix looks solid to me.

@visch Yup, and column type merging too.

**Review by visch — APPROVED** [review]
Looks fine to me I'm just a bit confused as to why our existing test doesn't hit this here https://github.com/MeltanoLabs/target-postgres/blob/d86410609512ebdd4900deb91fb0c737d3df1986/target_postgres/tests/test_target_postgres.py#L397-L399 

Expanding that test to include this code path in the SDK would be nice too. Does the SDK sort function only get hit when you have multiple types?

**Comment by edgarrmondragon** [comment]
> Looks fine to me I'm just a bit confused as to why our existing test doesn't hit this here https://github.com/MeltanoLabs/target-postgres/blob/d86410609512ebdd4900deb91fb0c737d3df1986/target_postgres/tests/test_target_postgres.py#L397-L399 
> 
> Expanding that test to include this code path in the SDK would be nice too. Does the SDK sort function only get hit when you have multiple types? 

@visch that's a good point. I'll check the SDK implementation to see when this is called and why the tests weren't triggering it.

**Pull request merged**
